version: "3.9"
services:
  cuttube-api:
    build:
      context: ./cuttube-api
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./cuttube-api/src:/home/app/src
    ports:
      - 5000:5000
    networks:
      - cuttube-net

  cuttube-app:
    build:
      context: ./cuttube-app
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./cuttube-app:/home/app
      - /home/app/node_modules
    ports:
      - 5173:5173
    networks:
      - cuttube-net

networks:
  cuttube-net: